# Generated by Django 2.2.9 on 2020-01-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('apellido_paterno', models.CharField(max_length=150)),
                ('apellido_materno', models.CharField(max_length=150)),
                ('direccion', models.TextField()),
                ('telefono', models.IntegerField()),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de Creacion')),
            ],
        ),
    ]
