# Generated by Django 2.2.9 on 2020-01-27 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20200122_0903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nombre'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Users'},
        ),
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('serie', models.CharField(max_length=150)),
                ('detalles', models.CharField(max_length=150)),
                ('costo', models.CharField(max_length=6)),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de Creacion')),
                ('usuario_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario')),
            ],
            options={
                'verbose_name': 'Computadora',
                'verbose_name_plural': 'Computers',
                'ordering': ['nombre'],
            },
        ),
    ]
