# Generated by Django 2.2.9 on 2020-01-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20200127_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computadora',
            name='detalles',
            field=models.TextField(),
        ),
    ]
