# Generated by Django 2.2.9 on 2020-01-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20200127_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computadora',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='computadora',
            name='usuario_id',
            field=models.ManyToManyField(to='usuarios.Usuario'),
        ),
    ]
