# Generated by Django 2.2.9 on 2020-03-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_computadora_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='computadora',
            name='descripcion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
